# Generated by Django 3.2 on 2021-09-10 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HitcountHit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_pk', models.IntegerField()),
                ('content_type_id', models.IntegerField()),
                ('modified', models.DateTimeField()),
                ('hits', models.IntegerField()),
            ],
            options={
                'db_table': 'hitcount_hit_count',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HitcountHitcount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=40)),
                ('session', models.CharField(max_length=40)),
                ('user_agent', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'hitcount_hit',
                'managed': False,
            },
        ),
    ]
